project_name: neocode
version: 2

before:
  hooks:
    - go mod tidy
    - go mod download

builds:
  - id: neocode
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'neo-code/internal/version.Version={{.Version}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/neocode/main.go
    binary: neocode

  - id: neocode-gateway
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X 'neo-code/internal/version.Version={{.Version}}'
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    main: ./cmd/neocode-gateway/main.go
    binary: neocode-gateway

archives:
  - id: neocode
    ids:
      - neocode
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      neocode_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

  - id: neocode-gateway
    ids:
      - neocode-gateway
    format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    name_template: >-
      neocode-gateway_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}

checksum:
  name_template: checksums.txt

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
