package help

import (
	"context"
	"strings"
	"testing"

	"neo-code/internal/tuiv2/gateway"
	"neo-code/internal/tuiv2/kernel"
	"neo-code/internal/tuiv2/state"

	tea "github.com/charmbracelet/bubbletea"
)

// fakeHost 提供预置绑定快照。
var _ kernel.Host = (*fakeHost)(nil)

type fakeHost struct {
	bindings []kernel.Binding
	overlays []kernel.Overlay
}

func newFakeHost() *fakeHost {
	return &fakeHost{bindings: []kernel.Binding{
		{Mode: state.NormalMode, Key: "j", Description: "下滚"},
		{Mode: state.LeaderMode, Key: "p", Description: "面板", Group: "面板"},
		{Mode: state.LeaderMode, Key: "x", Description: "无分组动作"},
	}}
}

func (h *fakeHost) State() *state.ViewState                        { return state.NewViewState() }
func (h *fakeHost) Gateway() gateway.Client                        { return nil }
func (h *fakeHost) GoCmd(cmd tea.Cmd)                              {}
func (h *fakeHost) Send(msg tea.Msg)                               {}
func (h *fakeHost) Mode() state.InputMode                          { return state.NormalMode }
func (h *fakeHost) SetMode(m state.InputMode)                      {}
func (h *fakeHost) PushOverlay(o kernel.Overlay)                   { h.overlays = append(h.overlays, o) }
func (h *fakeHost) PopOverlay()                                    {}
func (h *fakeHost) Confirm(req state.ConfirmRequest)               {}
func (h *fakeHost) Notify(text string)                             {}
func (h *fakeHost) Quit()                                          {}
func (h *fakeHost) Commands() []kernel.Command                     { return nil }
func (h *fakeHost) RunCommand(string, []string) error              { return nil }
func (h *fakeHost) Bindings() []kernel.Binding                     { return h.bindings }
func (h *fakeHost) BindEventStream(ch <-chan gateway.GatewayEvent) {}

func TestPluginIdentityAndBindings(t *testing.T) {
	p := New()
	if p.ID() != "help" {
		t.Fatalf("id = %q", p.ID())
	}
	bs := p.Bindings()
	if len(bs) != 1 || bs[0].Key != "h" {
		t.Fatalf("bindings = %+v", bs)
	}
}

func TestOpenRendersBindingsAutoGenerated(t *testing.T) {
	p := New()
	h := newFakeHost()
	// 打开：经 Leader h 绑定。
	for _, b := range p.Bindings() {
		b.OnKey(h)
	}
	if len(h.overlays) != 1 {
		t.Fatal("open should push help overlay")
	}
	out := h.overlays[0].View(h, 80)
	if !strings.Contains(out, "ctrl+c") || !strings.Contains(out, "下滚") || !strings.Contains(out, "面板") {
		t.Fatalf("help view should include reserved key and bindings, got %q", out)
	}
}

func TestOverlayAnyKeyCloses(t *testing.T) {
	p := New()
	h := newFakeHost()
	p.open(h)
	if len(h.overlays) != 1 {
		t.Fatal("open should push overlay")
	}
	// 任意键关闭（PopOverlay 由 fake host 计数间接验证——直接验证 consumed）。
	consumed := h.overlays[0].HandleKey(h, tea.KeyMsg{Type: tea.KeyRunes, Runes: []rune("x")})
	if !consumed {
		t.Fatal("help overlay should consume any key to close")
	}
}

func TestLifecycle(t *testing.T) {
	p := New()
	p.Init(context.Background(), nil)
	p.Close(context.Background())
}

// TestHelpLifecycleAndModeName 补齐身份/生命周期/modeName 分支。
func TestHelpLifecycleAndModeName(t *testing.T) {
	p := New()
	if p.ID() != "help" {
		t.Fatalf("id = %q", p.ID())
	}
	p.Init(context.Background(), newFakeHost())
	p.Close(context.Background())
	// modeName 分支：Leader 名称（经 View 断言——预置 Leader 绑定已在 fakeHost）。
	h := newFakeHost()
	p.open(h)
	out := h.overlays[0].View(h, 80)
	if !strings.Contains(out, "Leader 模式") || !strings.Contains(out, "面板  p  面板") {
		t.Fatalf("view should contain leader group and grouped entry, got %q", out)
	}
}

// TestOverlayEscCloses：esc 关闭帮助浮层。
func TestOverlayEscCloses(t *testing.T) {
	p := New()
	h := newFakeHost()
	p.open(h)
	consumed := h.overlays[0].HandleKey(h, tea.KeyMsg{Type: tea.KeyEsc})
	if !consumed {
		t.Fatal("esc should close help overlay")
	}
}

// TestSortedKeysHelper：排序 helper（未导出覆盖）。
func TestSortedKeysHelper(t *testing.T) {
	got := sortedKeys([]kernel.Binding{
		{Key: "b", Mode: state.NormalMode},
		{Key: "a", Mode: state.LeaderMode},
	})
	if len(got) != 2 || got[0] != "a" || got[1] != "b" {
		t.Fatalf("sortedKeys = %v", got)
	}
}

// TestHelpInputModeNameBranch 补齐 modeName 的输入模式分支。
func TestHelpInputModeNameBranch(t *testing.T) {
	h := newFakeHost()
	h.bindings = append(h.bindings, kernel.Binding{
		Mode: state.InputModeInput, Key: "any", Description: "输入编辑", OnKeyMsg: func(h kernel.Host, msg tea.KeyMsg) {},
	})
	p := New()
	p.open(h)
	out := h.overlays[0].View(h, 80)
	if !strings.Contains(out, "输入模式") {
		t.Fatalf("view should contain input mode group, got %q", out)
	}
}

// TestOverlayAndPluginID 补齐两个 ID 方法的覆盖。
func TestOverlayAndPluginID(t *testing.T) {
	p := New()
	h := newFakeHost()
	if got := p.ID(); got != "help" {
		t.Fatalf("plugin id = %q", got)
	}
	p.open(h)
	if got := h.overlays[0].ID(); got != "help" {
		t.Fatalf("overlay id = %q", got)
	}
}
